// Initial Datasets for Jira Access Management

export const INITIAL_PROJECTS = [
  {
    id: "proj-1",
    key: "PROJ-CORE",
    name: "Payment Gateway Core",
    description: "Core banking and checkout transaction engine.",
    category: "Financial Engineering",
    accessibleDashboards: 6,
    securityLevel: "Strict / Admin Only",
  },
  {
    id: "proj-2",
    key: "PROJ-MOB",
    name: "Mobile App V2",
    description: "Next-gen iOS & Android customer native application.",
    category: "Mobile Product",
    accessibleDashboards: 4,
    securityLevel: "Standard Restricted",
  },
  {
    id: "proj-3",
    key: "PROJ-CLOUD",
    name: "Cloud Infrastructure",
    description: "Kubernetes orchestration, Terraform IAC & AWS clusters.",
    category: "DevOps & Platform",
    accessibleDashboards: 8,
    securityLevel: "Mission Critical",
  },
  {
    id: "proj-4",
    key: "PROJ-DS",
    name: "Design System & UI",
    description: "Glitter Blue design tokens, React component libraries.",
    category: "Product Design",
    accessibleDashboards: 3,
    securityLevel: "Public Internal",
  },
  {
    id: "proj-5",
    key: "PROJ-AI",
    name: "AI Copilot Engine",
    description: "LLM integration pipeline and RAG search indexer.",
    category: "Data Science",
    accessibleDashboards: 5,
    securityLevel: "Restricted Confidential",
  },
];

export const INITIAL_PEOPLE = [
  {
    id: "usr-1",
    name: "Alex Rivera",
    email: "alex.rivera@jira.internal",
    role: "Senior Lead Architect",
    avatarBg: "bg-blue-600",
    accessibleProjectIds: ["proj-1", "proj-3", "proj-5"],
  },
  {
    id: "usr-2",
    name: "Sarah Chen",
    email: "sarah.chen@jira.internal",
    role: "Fullstack Engineer",
    avatarBg: "bg-purple-600",
    accessibleProjectIds: ["proj-1", "proj-2"],
  },
  {
    id: "usr-3",
    name: "Marcus Vance",
    email: "marcus.vance@jira.internal",
    role: "DevOps Lead",
    avatarBg: "bg-cyan-600",
    accessibleProjectIds: ["proj-1", "proj-3"],
  },
  {
    id: "usr-4",
    name: "Elena Rostova",
    email: "elena.rostova@jira.internal",
    role: "UI/UX Principal",
    avatarBg: "bg-emerald-600",
    accessibleProjectIds: ["proj-2", "proj-4"],
  },
  {
    id: "usr-5",
    name: "David Kim",
    email: "david.kim@jira.internal",
    role: "Backend Engineer",
    avatarBg: "bg-indigo-600",
    accessibleProjectIds: ["proj-1", "proj-4", "proj-5"],
  },
  {
    id: "usr-6",
    name: "Priya Sharma",
    email: "priya.sharma@jira.internal",
    role: "Product Manager",
    avatarBg: "bg-amber-600",
    accessibleProjectIds: ["proj-2", "proj-4"],
  },
  {
    id: "usr-7",
    name: "Lucas Bennett",
    email: "lucas.bennett@jira.internal",
    role: "QA Automation Specialist",
    avatarBg: "bg-teal-600",
    accessibleProjectIds: ["proj-4", "proj-5"],
  },
];

export const INITIAL_LOGS = [
  {
    id: "log-1",
    timestamp: "2026-08-13T08:45:00.000Z",
    actor: "Provisioning Admin",
    action: "ACCESS_GRANTED",
    targetPerson: "Alex Rivera",
    targetProject: "AI Copilot Engine",
    details: "Granted access to AI Copilot Engine (5 dashboards)",
    ipAddress: "—",
  },
  {
    id: "log-2",
    timestamp: "2026-08-13T07:00:00.000Z",
    actor: "Provisioning Admin",
    action: "ADMIN_LOGIN",
    targetPerson: "Provisioning Admin",
    targetProject: "Security Vault",
    details: "Admin authenticated via Single Sign-On Gateway",
    ipAddress: "—",
  },
  {
    id: "log-3",
    timestamp: "2026-08-13T04:00:00.000Z",
    actor: "Provisioning Admin",
    action: "ACCESS_REVOKED",
    targetPerson: "Priya Sharma",
    targetProject: "Payment Gateway Core",
    details: "Revoked project access & associated dashboard permissions",
    ipAddress: "—",
  },
  {
    id: "log-4",
    timestamp: "2026-08-12T09:00:00.000Z",
    actor: "Provisioning Admin",
    action: "PROJECT_PROVISIONED",
    targetPerson: "Provisioning Admin",
    targetProject: "Design System & UI",
    details: "Provisioned new Task Project 'Design System & UI' with 3 linked dashboards",
    ipAddress: "—",
  },
];
